### ISSUE TITLE
question on permissions

### ISSUE THREAD

**Issue by IzzySoft** [tateisu/SubwayTooter#274]
For the last update, our scanners report:

```
! repo/jp.juggler.subwaytooter.noFcm_547.apk declares sensitive permission(s):
  android.permission.READ_EXTERNAL_STORAGE android.permission.READ_MEDIA_IMAGES
  android.permission.READ_MEDIA_VIDEO android.permission.READ_MEDIA_AUDIO
! repo/jp.juggler.subwaytooter.noFcm_547.apk contains signature block blobs: 0x504b4453 (DEPENDENCY_INFO_BLOCK; GOOGLE)
```

Can you please clarify what those permissions are needed/used for? As for `DEPENDENCY_INFO_BLOCK`, that can easily be avoided with a small addition to your `build.gradle`:

```gradle
android {
    dependenciesInfo {
        // Disables dependency metadata when building APKs.
        includeInApk = false
        // Disables dependency metadata when building Android App Bundles.
        includeInBundle = false
    }
}
```

For some background: that BLOB is supposed to be just a binary representation of your app's dependency tree. But as it's encrypted with a public key belonging to Google, only Google can read it – and nobody else can even verify what it really contains. More details can be found e.g. here: [Ramping up security: additional APK checks are in place with the IzzyOnDroid repo](https://android.izzysoft.de/articles/named/iod-scan-apkchecks#blobs).

Thanks in advance!

**Comment by tateisu** [comment]
this app switch  os's media picker by allowed permission.
- Android 14 media picker is used when permission is "allow restricted",
the app can access media which user choosed in OS side picker, any other
media can't  be read from the app.
- pre-14 media picker is used when permission is " allowed", it can refer
all media, also use other apps that can work as picker, such as "Google
Drive", that can pick media from those own collection.
the use can choose picker experience by app's media permission.

2024年12月30日(月) 19:49 Izzy ***@***.***>:

**Comment by tateisu** [comment]
Usually Android 14's media permission Dialog shows  "allow with
restriction" as first choice, then many users  on Android14+ go with more
secure way.
but if user re-select media permission in os's app info, ST also support
pre-14 age media selection.

2024年12月30日(月) 22:10 tateisu ***@***.***>:

**Comment by tateisu** [comment]
***@***.***/111711694086073615

2024年12月30日(月) 22:17 tateisu ***@***.***>:

**Comment by IzzySoft** [comment]
Thanks! Added those permissions to the app's "green list":

```yaml
    android.permission.READ_EXTERNAL_STORAGE: used on lower Android versions to access media for inclusion with toots
    android.permission.READ_MEDIA_IMAGES: used on higher Android versions to access image files for inclusion with toots
    android.permission.READ_MEDIA_VIDEO: used on higher Android versions to access video files for inclusion with toots
    android.permission.READ_MEDIA_AUDIO: used on higher Android versions to access audio files for inclusion with toots
```

Will you address the `DEPENDENCY_INFO_BLOCK`?
